### PR TITLE
Resolve #155 Show Transcriptions in Feed

### LINKED ISSUE #155: Show Transcriptions in Feed
**Describe the feature. What should a user be able to do?**
As a user I should be able to see and read transcriptions in the content feed. The transcriptions should be toggle displayable by the user below the content.

**Why do we need this feature?**
This will allow people to read what people have submitted.

### PR DESCRIPTION
**Pull request by mzagaja**
* For all responses show a toggable transcription in the story feed

### CODE REVIEW

**Comment by ericyoungberg** [comment]
I can't test this because I can't upload an audio file from FF on Mojave. Looks like the direct upload tries to put it into Google, but I get an error after submission saying that "Response must be provided".

**Comment by mzagaja** [comment]
@ericyoungberg Can you test video upload instead of audio or just typing a response? I have checked and develop at cce034af2d329a8beba9e02dd1e1ea693b2507f7 works fine on staging for audio. This bug is likely unrelated to this pull request and should probably earn its stripes as its own issue.

**Comment by mzagaja** [comment]
Does Firefox have an option to disable cross origin restrictions? That should fix it on localhost. At least that is the feature that seems to toggle the issue for me in Safari on macOS.

**Comment by mzagaja** [comment]
CORS issue should be resolved by https://github.com/MAPC/digitalhub/commit/a5e8a97c6b2a2b15a56d19a120fbd97f603ff133

**Comment by ericyoungberg** [comment]
The Google upload appears to work even though I can't submit.

screen shot 2019-02-14 at 9 10 17 am

**Pull request closed without merging**
