### PR TITLE
Resolve #385 Implement External Translation Service

### LINKED ISSUE #385: Implement External Translation Service
**Describe the feature. What should a user be able to do?**
When a user clicks a language from the language drop down we should reload the page using an external translation service in an IFRAME.

**Why do we need this feature?**
Although we initially believed that we were going to get content professionally translated, this turned out to be an expensive and time consuming endeavor. Furthermore the lack of use of the translated content feature has meant that it has been unevenly implemented in new work. Finally users and others in the field have suggested that using machine translations and presenting it as "translated" content is misleading to users.

A second thread of reasoning involves complexity and technical debt. Implementing translation into each new feature is a bit tedious and acts as an additional tax on implementing features. In a separate issue we will attempt to back out the translation to reduce surface area of complexity of the application.

**Alternatives**
Paying for professional translations and paying the technical debt of implementation proved to be a bit much here.

We also considered removing the translation menu completely but implementation of the auto translate should be trivial and will also make accessing that easier for folks that do not yet use Chrome.

### PR DESCRIPTION
**Pull request by mzagaja**
* Update front-end to use Microsoft translation service.
* Remove or revert AWS translation layer.
* Remove language disclaimer and styles.

### CODE REVIEW

**Comment by smithWEBtek** [comment]
I'm getting this error for every language:  

`Sorry, that page doesn't exist or is preventing translations.`
en-pt

The URL works when I tried it from another site:
example-works

**Comment by mzagaja** [comment]
I sent a message to Microsoft Translation support about this since the online help doesn't explain how this works.

**Comment by mzagaja** [comment]
Waiting for follow-up form Microsoft after receiving an automated email from them.

**Comment by mzagaja** [comment]
Sent follow-up ping to Microsoft about this.

**Pull request merged**
