### PR TITLE
Resolve #199 Add Event End Time to Event Block

### LINKED ISSUE #199: Add event end time to event block
**Describe the feature. What should a user be able to do?**
As a user I should be able to see start and end time of the event when listed on the Events page.  

This would be a change from only start time to both start and end time.  Both fields are captured for each individual event.  Example (example 3:00 pm – 8:00 pm instead of just 3:00pm) 
screen shot 2019-02-07 at 1 58 27 pm

### PR DESCRIPTION
**Pull request by mzagaja**
* Add event end time to the event block in order to let the user see when the event ends.

### CODE REVIEW

**Comment by ericyoungberg** [comment]
Another interesting thing about the last one is that the render order changes. (By the way, I entered in a date that ends before it starts which is why you are seeing the 21st as the start with the 20th as the end.

one
two
three

**Comment by mzagaja** [comment]
I could not reproduce all the weirdness you screenshotted here but I dialed in some updates to what I did see. It should look better now. The changing of the render order is a design choice made by the previous developer and designer that did that, so we should not touch that in this PR.

**Comment by ericyoungberg** [comment]
What do you mean by "design choice made by the previous developer and designer that did that" when you are the developer who implemented this? The end date never existed before this PR. I just talked to Kit, and she never made design for this feature, so it couldn't have been her choice to have the end date show before the start date.

**Comment by mzagaja** [comment]
If you look at the status of the mobile view on the commit before the pull request you will note that the order of the render of the location and date is the same as after I added the end date:

image

This was DeeDee's design for the events page as implemented by Ian. I am merely extending it to add the ending time for the event next to the start time as outlined by the issue. This pull request does not change this behavior or design.

**Comment by ericyoungberg** [comment]
Well then by this far-off definition you've created, I can't approve your PR because the start time is no longer underneath the event title.

**Pull request merged**
