### PR TITLE
Remove migrations containing seed code

### LINKED ISSUE #395: Taggings Not Retrieved From Controller
**Describe the bug**
Upon load of `/find-out` page, all content types and all topic areas should appear.
Taggings controller error, json data not retreived.

```
jquery.min.js:2 GET https://staging.metrocommon.mapc.org/taggings.json?content_type=everything&topic_area=all%20topic%20areas 500
```

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Go to '/find-out
2. See error in browser dev tools

**Expected behavior**
User would expect to see all existing tagged items upon load of find-out page.
Page loads, but no items appear. 

If you select from either `content_type` or `topic_area` dropdowns, you do get expected results.
 
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] .   Mac OS
 - Browser [e.g. chrome, safari] .  Chrome
 - Version [e.g. 22] Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
New deployment of `develop` to `staging`.

### PR DESCRIPTION
**Pull request by smithWEBtek**
Resolves #395 

# Why is this change necessary?
There were 3 migrations containing seed data which should not be pushed to staging or production. Due to the load order of these files, data prematurely loaded which did not match the final schema of the database. This caused the taggings controller to fail at sorting data containing null values for `sort_date`, (specifically the Announcement `published_date`).

# How does it address the issue?
* Remove seed migrations for Announcement, Event and Report
* Remove code that seeds a single fake Event
* Remove the csv and png files associated with these ‘seed’ migrations

# What side effects does it have?
None. In a separate effort, these files and import code will be recreated in a rake task and a related folder for development locally.

### CODE REVIEW

**Comment by mzagaja** [comment]
This generally looks good, but should this also include a validation to make sure announcements have a `published_date` and a test for it?

**Comment by smithWEBtek** [comment]
Thanks, there was/is a test for it here:   `rspec spec/models/announcement_spec.rb:34`, and I have added a validation.

**Comment by mzagaja** [comment]
Ah I see now.
```
it "it MUST have a published_date", js: true do
    tag1 = Refinery::Tags::Tag.create(title: 'news', narrative: "We do announcements on a specific date.", tag_type: "content_type")
    announcement1 = FactoryBot.create(:announcement, title: 'Test Announcement Title', published_date: '02-03-2018')
    announcement1.tags.push(tag1)
    announcement1.save

    expect(announcement1.published_date.month).to eq(3)
  end
```
I think this test doesn't successfully test for what it claims to test after reviewing it here. In the second line you setup an announcement with a title and published date which is fine, and then assert (test for) that it has the date you set it up with. However, what you want to test for is the idea that we get a failure if the date is missing. The question we need the test to answer is will the app let us save something without a published_date and the desired result is no.
```
announcement = FactoryBot.build(:announcement, title: 'Test title', published_date: nil)
announcement.valid?
announcement.errors[:published_date].should include("can't be blank")
```
Give that a try for the test and see if it works.

**Comment by smithWEBtek** [comment]
This PR is recreated in #403

**Pull request closed without merging**
